- name: Schedule Build & Deploy Hooks
  # You may pin to the exact commit or the version.
  # uses: codemzy/schedule-build-action@3086f627e56069cccaced29ddc23b45f38effebf
  uses: https://api.vercel.com/v1/integrations/deploy/prj_5W6lomDnufu2SgWfsNVkyHMvjIfM/A5YWv2dShL
